import { LightningElement } from 'lwc';

export default class Atividade1 extends LightningElement {
    pessoa = [
        {
        id: 345345,
        primeironome:          "Jéssica" , 
        sobrenome:              "Lima", 
        idade:                  "28", 
        email:                  "je@cansada.cuom", 
        classificacao:          "hot" , 
        empresa:                "Salesforce" , 
        receitaanual:           2000000}, 
        ];
}
